### ISSUE TITLE
Shallow equals in mergeIntoEntity?

### ISSUE THREAD

**Issue by idolize** [gaearon/normalizr#18]
I am curious why lodash `isEqual` is used in this library ([isEqual is a *deep* equality check](https://lodash.com/docs#isEqual), and is very expensive).

I noticed it is used on [line 38](https://github.com/gaearon/normalizr/blob/master/src/index.js#L38) to compare newly-normalized entities against ones that already exist in the top-level list. But, then [if they are deeply equal, they are swapped](https://github.com/gaearon/normalizr/blob/master/src/index.js#L39)? What is the point of this exactly?

My guess is that there was an incorrect assumption made that `isEqual` is a *shallow* equality check, because the `console.warn` output on [line 43](https://github.com/gaearon/normalizr/blob/master/src/index.js#L43) says `"found shallowly unequal data"`.

**Comment by gaearon** [comment]
I think it was intentional, and the comment mismatches. If it wasn't deep, it would trigger warnings on any nested objects that may not even be part of the schema (e.g. `{ id: 2, location: { latitude: 42, longitude: 42 } }`).

Normalizr is primarily designed for handling AJAX responses and it's unlikely any performance problems with `isEqual` check outweigh network latency.
