### ISSUE TITLE
Qu: Why the equality check if isEqual(entityA[key], entityB[key]) in defaultMergeIntoEntity

### ISSUE THREAD

**Issue by smargh** [gaearon/normalizr#51]
This is another question in the same vein as #50. In `defaultMergeIntoEntity`, the only code branch that actually merges `entityA` and `entityB` runs as follows:
```
if (!entityA.hasOwnProperty(key) || isEqual(entityA[key], entityB[key])) {
  entityA[key] = entityB[key];
  continue;
}
```
I understand that first half of the `if` clause (if `entityA` does not already have `key` defined, we need to define it), but the second half confuses me. It seems to me that if `entityA[key]` is equal to `entityB[key]`, then there is no need to re-define it (as that would be redundant). However, it would make sense to me to re-define `entityA[key]` *if it were not equal* to `entityB[key]`.

So, I'm wondering, is this is typo/mistake/bug, or am I misunderstanding something?

**Comment by gaearon** [comment]
I think you can safely extract this check into a sibling `if` statement just below this one as long as you also `continue` when it's true. From what I remember the only reason it exists is to *not* warn (just a few lines below) in this case, as we only want to warn if the values are not deeply equal.

It also seems marginally better to hold onto fewer object instances, so if we can use just one of two deeply (but not referentially) equal objects instead of two, it's a small win. (I doubt it matters though.)
