### ISSUE TITLE
Entities from other Stores?

### ISSUE THREAD

**Issue by ericclemmons** [gaearon/normalizr#7]
If I have an `AuthorStore` and ` BookStore`, and request the `/api/authors/1` _currently_ returns:

```js
{
  id: 1,
  name: "Eric",
  books: [1,2,3,4]
}
```

Would it be best to transform this first into:

```js
{
  result: {
    id: 1,
    name: "Eric",
    books: [1,2,3,4]
  },
  entities: []
}
```

And then `payload.entities.push(...books)` where `books` comes from `BookStore.getAllBooks()`?

**Comment by gaearon** [comment]
Sorry, I don't quite understand what you're saying, can you give a more complete example / use case with “before” and “after”?

**Comment by gaearon** [comment]
Closing this, as I don't understand the issue. I don't think it's great to denormalize when data reaches the stores, because then you start to get all kinds of issues with referential equality. For example, `BookListStore` starts to reference *actual* books, and then some might update, and `BookStore` emits change but `BookListStore` doesn't—but the data that `BookListStore` returns is now different.. Meh.

[It's entirely possible](https://github.com/gaearon/flux-react-router-example) to lift all data from the stores in the components. I don't see the point of denormalizing before the change event is emitted.

**Comment by ericclemmons** [comment]
Fair enough.

The gist was (sorry it wasn't clear), requesting an entities from an API (e.g. `author`) will intrinsically have child entities that likely already exist in the app from a previous request (e.g.`books`).

Given the scenario that it's preferable to leave the child entities _out_ of the feed (to save tons of KB), how would you allow others (such as stores) to lookup & fill in the gaps for normalization?

**Comment by gaearon** [comment]
There's no way for API to know what data is already available in the app, is there? How would it know which entities to omit? If it's repetition you're worried about, it's usually not a big issue due to gzipping.

If it's a problem in your app, you should look into forming normalized responses *right on the server*.
